### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by Nekorara4** [monkenWu/TablesIgniter#10]
hi, i'm trying to implement this library with my ci-4 app.
but this always return error class not found.
i've already install composer and use monken\TablesIgniter on my app controller. 
idk why.. i'm currently use codeigniter 4.1.1.
and there is my sample sourcecode.

`
namespace App\Controllers;
use App\Controllers\BaseController;
use monken\TablesIgniter;
use App\Models\Transaction;
use CodeIgniter\API\ResponseTrait;
use CodeIgniter\RESTful\ResourceController;

public function otherdatatables()
	{
		$table = new TablesIgniter();
		$Transaction = new Transaction();
		$table->setTable($Transaction->datatableList())
			->setDefaultOrder("id", "DESC")
			->setOutput([
				"id",
				"buyer",
				"created_at as created"
			]);
		return $table->getDatatable();
	}
`

**Comment by monkenWu** [comment]
Hello there!
Does the PHP file `{Project Root} /vendor/monken/tablesigniter/src/TablesIgniter.php` exist?

**Comment by Nekorara4** [comment]
no, there is only .circle, app, public, tests, writeable folder.
im Using version ^1.1 for monken/tablesigniter

**Comment by monkenWu** [comment]
You must install Codeigniter4 through [Composer ](https://codeigniter.com/user_guide/installation/installing_composer.html) to use this library.

**Comment by germs2611** [comment]
Hey, am having the same problem even though I install and create the project with composer. There is no /vendor/monken/src/TablesIgniter.php file. Hence Class "monken\TablesIgniter" not found error.

**Comment by germs2611** [comment]
The library files are not been downloaded.

**Comment by monkenWu** [comment]
@germs2611 
Hi,Have you installed the library using the following commands in your project-root directory?
`composer require monken/tablesigniter`
If you executed the installation command, please check if the following files exist:
`{Project Root} /vendor/monken/tablesigniter/src/TablesIgniter.php`

**Comment by germs2611** [comment]
Yes I did. I even created a another project from scratch using composer an when a I ran the command composer require monken/tablesigniter in the project root the same thing happen. That src folder is not showing up.

![image](https://user-images.githubusercontent.com/73079191/116785634-81197680-aa4f-11eb-9dc5-f4760d686d8c.png)

**Comment by germs2611** [comment]
I have downloaded the zip file. Can it be added manually by creating the src folder and if so how do I add it to be auto loaded.

**Comment by monkenWu** [comment]
Hi
I don't see "vendor" in your directory structure, can you try to execute the following command in the project root directory?
`composer install`

**Comment by germs2611** [comment]
![image](https://user-images.githubusercontent.com/73079191/116812386-5f79c700-ab03-11eb-81f7-2e9b1edcc018.png)

**Comment by 1m-Arthur** [comment]
Hi guys, 
i have the same problem, but i solve this problem with manually adding **this repo on library branch** to my ~~`app_path/vendor/monken/tablesigniter/src/`~~
`${your_project_path}/vendor/monken/tablesigniter/src/`

hopefully solve your problem
cheers~

**Comment by germs2611** [comment]
Hi 1m-Arthur, could you tell me exactly which file am suppose to put that in C4. Or if you have a snippet.

Thanks.

**Comment by 1m-Arthur** [comment]
Hi @germs2611, you can clone or download this.
`https://github.com/monkenWu/TablesIgniter/tree/library`

**Comment by germs2611** [comment]
Hi @1m-Arthur, I have downloaded he file but I want to know how I add it to my project. Create a src folder and add the TablesIgniter.php file and how do I add to the APPPATH.

Thanks

**Comment by 1m-Arthur** [comment]
@germs2611 
whoops, i'm sorry.
if you already done adding this file
`${your_project_path}/vendor/monken/tablesigniter/src/TablesIgniter.php`
to your project path.
that's mean this library is ready to use and you can try some [Quick Start guide](https://github.com/monkenWu/TablesIgniter/blob/master/README.md#quick-start).

**Comment by germs2611** [comment]
Hi @1m-Arthur, sorry for the confusion. I tried your steps before but am wondering if am missing something. The CI4 framework throwing a Class "monken\TablesIgniter" not found error. The autoloader not finding the TablesIgniter.php file when I add it manually. Is there some other configuration that am suppose to do so it can find it.

Thanks

**Comment by monkenWu** [comment]
@germs2611 
Hi, can you provide the "monken/tablesigniter" part of "composer.json" and "composer.lock"?
These files will appear in your project root directory.

**Comment by germs2611** [comment]
Hi @monkenWu 
![image](https://user-images.githubusercontent.com/73079191/116818750-d8881700-ab21-11eb-880f-c45df236b5cc.png)

![image](https://user-images.githubusercontent.com/73079191/116818829-2b61ce80-ab22-11eb-8f22-1ad3083128e5.png)

**Comment by monkenWu** [comment]
@germs2611 

Please try to delete the library and reinstall the specified version.

`composer remove monken/tablesigniter`
`composer require monken/tablesigniter==1.2.0`

Then check whether the content in the specified directory looks like the picture below.

<img width="160" alt="擷取" src="https://user-images.githubusercontent.com/55150513/116819215-a6b69500-aba1-11eb-8f78-4de207a49763.PNG">

**Comment by germs2611** [comment]
Hi @monkenWu am getting the below error when trying to reinstall with specific version.

![image](https://user-images.githubusercontent.com/73079191/116819560-64e80900-ab25-11eb-9818-73ecb395b75a.png)

**Comment by monkenWu** [comment]
@germs2611 

What's your PHP version?

**Comment by germs2611** [comment]
Hi @monkenWu PHP version is 8.0.3

**Comment by germs2611** [comment]
Its seems like composer was using some old version of PHP. I ran it again with the --ignore-platform-reqs option and it works.

**Comment by monkenWu** [comment]
@germs2611
@1m-Arthur
@404Nekorara
Hi, this problem is caused because Tablesigniter only supports PHP7.
The new version V1.2.1 starts to support PHP 8.0, you can directly use `composer require monken/tablesigniter` to install Tablesigniter.
