### ISSUE TITLE
Undefined index: draw

### ISSUE THREAD

**Issue by barentshavet** [monkenWu/TablesIgniter#3]
I tried to follow the guide and get the following error

`Undefined index: draw`

Not sure what the problem is?

**Comment by monkenWu** [comment]
Hi, in the [official datatables doc](https://datatables.net/manual/server-side) ,it is mentioned that the function of the "draw" index is to draw the counter.
Please try to find out if the draw index exists in the ajax request.
like this:
![](https://i.imgur.com/DLS0Eq2.png)

**Comment by barentshavet** [comment]
Thanks for the quick reply.
Actually, I found out the issue was CSRF.

Do you have any examples of how to send the CSRF tokens with the Ajax request?

**Comment by monkenWu** [comment]
Okay,I see.
You can read [CI4 User Guide - Security Class](https://codeigniter4.github.io/userguide/libraries/security.html),It is the built-in security library of Codeigniter4. .
You can use "csrf token ()" and "csrf hash ()" to create the CSRF certification field attached to the ajax post.
Your datatables initialization code may look like this
```javascript
$('#fullTable').DataTable({
    "aoColumnDefs": [{ 
        "bSortable": false,
        "aTargets": [ 0,1 ] 
    }],
    "order":[],
    "serverSide":true,
    "ajax":{
        url:"<?=base_url('home/fullTable')?>",
        type:'POST',
        data : {
            <?=csrf_token()?> : "<?=csrf_hash()?>"
        }
    }
});
```
In the user guide,other configurations will be explained in detail, thank you.
